# Generated by Django 3.1.3 on 2020-11-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201112_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.URLField(default=''),
        ),
    ]
